site_name: SDK Documentation
use_directory_urls: true
nav:
  - Home: 
    - Introduction: 'index.md'
    - Setup: 'setup.md'
    - API overview: 'api/general.md'
    - Example C++: 'api/cpp.md'
    - Example Python: 'api/python.md'
    - Generation from NoCode (experimental): 'api/nocode.md'

markdown_extensions:
  - attr_list
  - md_in_html

theme: readthedocs

extra:
  version:
    provider: mike
